// roomData.js
export const roomData = [
    {
      title: "Junior Suite",
      image: "/img/room-1.jpg",
      price: "$100/Night",
      beds: 3,
      baths: 2,
      wifi: true,
    },
    {
      title: "Executive Suite",
      image: "/img/room-2.jpg",
      price: "$120/Night",
      beds: 3,
      baths: 2,
      wifi: true,
    },
    {
      title: "Super Deluxe",
      image: "/img/room-3.jpg",
      price: "$150/Night",
      beds: 3,
      baths: 2,
      wifi: true,
    },
    {
      title: "Presidential Suite",
      image: "/img/room-3.jpg",
      price: "$200/Night",
      beds: 2,
      baths: 2,
      wifi: true,
    },
    {
      title: "Luxury Suite",
      image: "/img/room-2.jpg",
      price: "$250/Night",
      beds: 4,
      baths: 3,
      wifi: true,
    },
    {
      title: "Beachfront Suite",
      image: "/img/room-1.jpg",
      price: "$300/Night",
      beds: 3,
      baths: 2,
      wifi: true,
    },
    {
      title: "Royal Suite",
      image: "/img/room-1.jpg",
      price: "$350/Night",
      beds: 4,
      baths: 3,
      wifi: true,
    },
    {
      title: "Sky Suite",
      image: "/img/room-2.jpg",
      price: "$400/Night",
      beds: 3,
      baths: 2,
      wifi: true,
    },
    {
      title: "Ocean View Suite",
      image: "/img/room-3.jpg",
      price: "$450/Night",
      beds: 3,
      baths: 2,
      wifi: true,
    },
  ];
  